SELECT DISTINCT
    M.MEETING_METHOD_CODE AS "METHOD_CODE"
   ,M.OWNING_BRANCH_CODE AS "OWNING_BRANCH_CODE"
   ,M.MEETING_KEY AS "MEETING_KEY"
FROM
    SALES.MEETING M
LEFT JOIN
    DIMENSIONS.NEW_CLIENT_DIMENSION N ON N.GCI = M.GCI_NUMBER
    AND M.STATUS_CODE = 'COMPLETED'
    AND DATE(M.MEETING_START_DATE_TIME) >= DATE(DAYS(CURRENT_DATE) - 365)
WHERE
    N.CLIENT_ACTIVE_YN = 'Y'
    AND (N.GCI LIKE 'G%' OR N.GCI LIKE '0%')
    AND (N.CUSTOMER_ORGANIZATION_ID = '${Account_Id}')
