SELECT DISTINCT
    O.OPPORTUNITY_STATUS_CODE AS "OPPORTUNITY_STATUS_CODE"
    ,IC.BRANCH AS "OWNING_BRANCH_CODE"
    ,O.OPPORTUNITY_KEY AS "OPPORTUNITY_KEY"
FROM
    SALES.OPPORTUNITY O
LEFT JOIN
    SALES.INTERNAL_CONTACT IC ON IC.EMPLOYEE_ID = O.OPPORTUNITY_OWNER_ID
WHERE
    O.ACCOUNT_ID = '${Account_Id}'
AND
    DATE(O.LAST_MODIFICATION_DATE_TIME) >= DATE(DAYS(CURRENT_DATE) - 365)
AND
    O.OPPORTUNITY_KEY IS NOT NULL