--VIZCRM

WITH

MR AS (
    SELECT
        UPPER(CONCAT(E.OWNING_BRANCH_CODE,E.GCI_NUMBER)) AS "EVENT_KEY",
        MAX(E.INSERT_DTTM) AS "INSERT_DTTM"
    FROM
        SALES.COMPANY_EVENT E
    WHERE
        E.COMPANY_EVENT_TYPE_CODE = 'STRG_INITIATV_IDNTFR'
        -- AND UPPER(E.COMPANY_EVENT_DESCRIPTION) IN ('STARTUPS')
    GROUP BY
        UPPER(CONCAT(E.OWNING_BRANCH_CODE,E.GCI_NUMBER))
),

CON AS (
    SELECT
        CON.COMPANY_EVENT_ID AS "COMPANY_EVENT_ID",
        MAX(CON.INSERT_DTTM) AS "INSERT_DTTM"
    FROM
        SALES.INTERNAL_COMPANY_EVENT_CONTACTS_LINK CON
    GROUP BY
        CON.COMPANY_EVENT_ID
)


SELECT DISTINCT
    CASE
        WHEN C.CUSTOMER_ORGANIZATION_ID = 'UNGROUPED' THEN E.GCI_NUMBER
        ELSE C.CUSTOMER_ORGANIZATION_ID
    END AS "ACCOUNT_ID",
    CASE
        WHEN E.CUSTOMER_ACCOUNT_MANAGEMENT_LEVEL_CODE IS NULL THEN 'SALES PIPELINE'
        ELSE E.CUSTOMER_ACCOUNT_MANAGEMENT_LEVEL_CODE
    END AS "ACC_MANAGEMENT",
    EC.EMPLOYEE_ID AS "EMPLOYEE_ID",
    E.CUSTOMER_ACCOUNT_OWNER_EMPLOYEE_ID AS "OWNER",
    P.PARTICIPANT_NAME AS "OWNER_NAME",
    P.BRANCH_CODE AS "OWNER_BRANCH",
    LISTAGG(DISTINCT T.TITLE_DESCRIPTION, ',') AS "OWNER_TITLE",
    T.EMPLOYEE_ID AS "MANAGER_ID" ,
        IC.FIRST_NAME AS "MANAGER_NAME",
        IC.LAST_NAME AS "MANAGER_LAST_NAME",
        IC.EMAIL_ADDRESS AS "MANAGER_EMAIL",
        IC.TITLE AS "MANAGER_TITLE",
    IC.BRANCH AS "MANAGER_BRANCH",
    E.GCI_NUMBER AS "GCI_NUMBER"
FROM
    SALES.COMPANY_EVENT E
INNER JOIN
    MR ON UPPER(CONCAT(E.OWNING_BRANCH_CODE,E.GCI_NUMBER)) = MR.EVENT_KEY AND E.INSERT_DTTM = MR.INSERT_DTTM
INNER JOIN
    SALES.INTERNAL_COMPANY_EVENT_CONTACTS_LINK EC ON E.COMPANY_EVENT_ID = EC.COMPANY_EVENT_ID

INNER JOIN
    CON ON EC.COMPANY_EVENT_ID = CON.COMPANY_EVENT_ID AND EC.INSERT_DTTM = CON.INSERT_DTTM
INNER JOIN
    DIMENSIONS.NEW_CLIENT_DIMENSION C ON E.GCI_NUMBER = C.GCI AND C.CLIENT_ACTIVE_YN = 'Y'
LEFT JOIN
        SALES.TEAM_MEMBER_ROLE T ON T.ACCOUNT_ID = C.CUSTOMER_ORGANIZATION_ID 
INNER JOIN
        SALES.INTERNAL_CONTACT IC on IC.EMPLOYEE_ID = T.EMPLOYEE_ID AND IC.USER_STATUS_CODE = 'Active' AND IC.TITLE LIKE ('%Account Manager%')
INNER JOIN
    DIMENSIONS.NEW_BRANCH_DIMENSION B
ON
    (LEFT(E.OWNING_BRANCH_CODE,3) = B.BRANCH_CODE OR RIGHT(E.OWNING_BRANCH_CODE,3) = B.BRANCH_CODE)
    AND B.OPERATIONAL_BRANCH_INDICATOR = 'Y'
LEFT JOIN 
    DIMENSIONS.PARTICIPANT_DIMENSION P
ON
    P.EMPLOYEE_ID = E.CUSTOMER_ACCOUNT_OWNER_EMPLOYEE_ID
--    AND SUBSTR( CAST(P.LOAD_YEAR_AND_MONTH AS VARCHAR), 1, 4) >=  YEAR(CURRENT DATE) -1
--    AND CAST(SUBSTR(CAST(P.LOAD_YEAR_AND_MONTH AS VARCHAR), 5, 6) AS INT) = CAST (MONTH(CURRENT DATE)-1  AS VARCHAR)
LEFT JOIN
    DIMENSIONS.TITLE_DIMENSION T ON T.TITLE_KEY= P.PARTICIPANT_TITLE_KEY
WHERE

    E.ACCOUNT_ID = '${Account_Id}'

GROUP BY
P.BRANCH_CODE,
IC.TITLE,
IC.BRANCH,
T.EMPLOYEE_ID,
        IC.FIRST_NAME,
        IC.LAST_NAME,
        IC.EMAIL_ADDRESS,
    E.CUSTOMER_ACCOUNT_MANAGEMENT_LEVEL_CODE,
    E.CUSTOMER_ACCOUNT_OWNER_EMPLOYEE_ID,
    P.PARTICIPANT_NAME,
    P.SALESPERSON_STATUS,
    UPPER(CONCAT(EC.EMPLOYEE_ID,CASE WHEN C.CUSTOMER_ORGANIZATION_ID = 'UNGROUPED' THEN E.GCI_NUMBER ELSE C.CUSTOMER_ORGANIZATION_ID END)),
    E.OWNING_BRANCH_CODE,
    CASE WHEN E.OWNING_BRANCH_CODE IN('NOG/NOX','CJS/ELP') THEN 'MEXICO/SOUTHERN BORDER' ELSE B.REGION_PL_NAME END,
    B.REGION_GEO_NAME1,
    UPPER(C.MASTER_CLIENT_REPORTING),
    CASE WHEN C.CUSTOMER_ORGANIZATION_ID = 'UNGROUPED' THEN E.GCI_NUMBER ELSE C.CUSTOMER_ORGANIZATION_ID END,
    EC.EMPLOYEE_ID,
    CASE WHEN C.CUSTOMER_ORGANIZATION_ID = 'UNGROUPED' THEN 'GCI' ELSE 'ACCOUNT' END
    ,E.GCI_NUMBER