WITH

DNA AS (
    SELECT
        NA.GCI_NUMBER AS "GCI"
        ,NA.CUSTOMER_ACCOUNT_ID AS "CUSTOMER_ACCOUNT_ID"
        ,CASE WHEN COUNT(NA.REPORT_KEY) >= 1 THEN 'DNA' ELSE 'NO DNA' END AS "IS_IN_PROGRAM"
        ,CASE WHEN COUNT(NA.REPORT_KEY) >= 1 THEN 'DNA' ELSE 'NO DNA' END AS "QUALIFIES_IN"
        ,STRING_AGG (I.DISPLAY_NAME, ',') AS "OWNERS"
        ,STRING_AGG(I.TITLE, ',')  AS "TITLES"
        ,MAX(NA.START_DATE) AS "START_DATE"
        ,STRING_AGG(I.BRANCH, ',') AS "BRANCH"
    FROM
        SALES.REPORT.SALES_NAMED_ACCOUNTS NA
    LEFT JOIN
        DWSALES.DBO.INTERNAL_CONTACT_DIMENSION I ON NA.EMPLOYEE_ID = I.EMPLOYEE_ID AND I.IS_CURRENT = 'Y'
    WHERE
        NA.CUSTOMER_ACCOUNT_ID = '${Account_Id}'
    AND
        NA.PROGRAM_TYPE IN ('DISTRICT_NAMED_ACCOUNT')
    GROUP BY 
        NA.CUSTOMER_ACCOUNT_ID
        ,NA.GCI_NUMBER 
),

GSE AS (
    SELECT
        NA.GCI_NUMBER AS "GCI"
        ,NA.CUSTOMER_ACCOUNT_ID AS "CUSTOMER_ACCOUNT_ID"
        ,CASE WHEN COUNT(NA.REPORT_KEY) >= 1 THEN 'DNA' ELSE 'NO DNA' END AS "IS_IN_PROGRAM"
        ,CASE WHEN COUNT(NA.REPORT_KEY) >= 1 THEN 'DNA' ELSE 'NO DNA' END AS "QUALIFIES_IN"
        ,STRING_AGG (I.DISPLAY_NAME, ',') AS "OWNERS"
        ,STRING_AGG(I.TITLE, ',')  AS "TITLES"
        ,MAX(NA.START_DATE) AS "START_DATE"
        ,STRING_AGG(I.BRANCH, ',') AS "BRANCH"
    FROM
        SALES.REPORT.SALES_NAMED_ACCOUNTS NA
    LEFT JOIN
        DWSALES.DBO.INTERNAL_CONTACT_DIMENSION I ON NA.EMPLOYEE_ID = I.EMPLOYEE_ID AND I.IS_CURRENT = 'Y'
    WHERE
        NA.CUSTOMER_ACCOUNT_ID = '${Account_Id}'
    AND
        NA.PROGRAM_TYPE IN ('GSE_NAMED_ACCOUNT')
    GROUP BY 
        NA.CUSTOMER_ACCOUNT_ID
        ,NA.GCI_NUMBER 
),

GTDP AS (
    SELECT
        I.GCI AS "GCI"
        ,I.CUSTOMER_ACCOUNT_NUMBER AS "CUSTOMER_ACCOUNT_ID"
        ,CASE WHEN COUNT(I.ROW_ID) >= 1 THEN 'GTDP' ELSE 'NO GTDP' END AS "IS_IN_PROGRAM"
        ,CASE WHEN COUNT(I.ROW_ID) >= 1 THEN 'GTDP' ELSE 'NO GTDP' END AS "QUALIFIES_IN"
        ,IDM.DISPLAY_NAME AS "OWNERS"
        ,IDM.TITLE AS "TITLES"
        ,I.EFFECTIVE_START_DATE AS "START_DATE"
        ,STRING_AGG(IDM.BRANCH, ',') AS "BRANCH"
    FROM
        LIST.NAMED_ACCOUNT_GTDP I
    LEFT JOIN
        SALES.IDENTITY_DIMENSION IDM ON I.OWNER_EMAIL = IDM.MAIL
    WHERE
        I.CUSTOMER_ACCOUNT_NUMBER = '${Account_Id}'
    GROUP BY 
        I.CUSTOMER_ACCOUNT_NUMBER
        ,IDM.DISPLAY_NAME
        ,IDM.TITLE
        ,I.EFFECTIVE_START_DATE
        ,I.GCI
)

SELECT
    CD.CUSTOMER_ORGANIZATION_ID AS "CUSTOMER_ACCOUNT_ID"
    ,CD.GCI  AS "GCI"
    ,AR.IS_IN_PROGRAM AS "IS_IN_PROGRAM"
    ,AR.QUALIFIES_IN AS "QUALIFIES_IN"
    ,AR.OWNERS AS "OWNERS"
    ,AR.TITLES AS "TITLES"
    ,CD.CLIENT_NAME AS "CLIENT_NAME"
    ,CD.ACCOUNT_TYPE AS "ACCOUNT_TYPE"
    ,CD.ADDR_LINE1 AS "ADDRESS"
    ,CD.CITY AS "CITY"
    ,CD.DUNS_NUMBER AS "DUNS_NUMBER"
    ,AR.BRANCH AS "BRANCH"
    ,CASE WHEN N.NEW_OR_EXISTING IS NULL THEN 'NO REVENUE' ELSE N.NEW_OR_EXISTING  END AS "STATUS"
    ,CASE WHEN CD.ACCOUNT_TYPE LIKE '%ADP%' THEN 'YES' ELSE 'NO' END AS "ADP"
FROM
    DWSALES.DBO.CLIENT_DIMENSION CD
LEFT JOIN
    ${Program} AR ON CD.CUSTOMER_ORGANIZATION_ID = CUSTOMER_ACCOUNT_ID AND AR.GCI = CD.GCI
LEFT JOIN
    SALES.REPORT.NEW_OR_EXISTING_GCIS N ON CD.GCI = N.GCI
WHERE
    CD.CUSTOMER_ORGANIZATION_ID = '${Account_Id}'
    AND AR.IS_IN_PROGRAM <> ''