WITH U AS(
    SELECT DISTINCT
        DMI.GLOBAL_ULTIMATE_DUNS_NUMBER
    FROM
        SALES.DUNS_MARKET_INSIGHT DMI
    INNER JOIN
        DIMENSIONS.NEW_CLIENT_DIMENSION NCD ON NCD.DUNS_NUMBER = DMI.DUNS_NUMBER AND NCD.CLIENT_ACTIVE_YN = 'Y'
    WHERE
        NCD.CUSTOMER_ORGANIZATION_ID = '${Account_Id}' OR NCD.MASTER_CLIENT_NUMBER = '${Account_Id}'
)

SELECT DISTINCT
    D.DUNS_NUMBER AS "DUNS_NUMBER"
    ,D.DOMESTIC_ULTIMATE_DUNS_NUMBER AS "DOMESTIC_ULTIMATE_DUNS_NUMBER"
    ,D.GLOBAL_ULTIMATE_DUNS_NUMBER AS "GLOBAL_ULTIMATE_DUNS_NUMBER"
    ,D.HQ_DUNS_NUMBER AS "HQ DUNS_NUMBER"
    ,D.PARENT_DUNS_NUMBER AS "PARENT_DUNS_NUMBER"
    ,CASE
        WHEN C.GCI IS NOT NULL THEN 'YES'
        ELSE 'NO'
    END AS "HAS_GCI_MATCH"
    ,C.GCI AS "GCI"
    ,D.SALES_BRANCH_CODE
    ,D.COUNTRY_NAME AS "COUNTRY"
    ,C.GCI_CITY AS "CITY"
    ,C.GCI_ZIP AS "ZIP CODE"
FROM
    SALES.DUNS_MARKET_INSIGHT_LARGE D
LEFT JOIN
    DIMENSIONS.NEW_CLIENT_DIMENSION C ON D.DUNS_NUMBER = C.DUNS_NUMBER AND CLIENT_ACTIVE_YN = 'Y'
WHERE
    D.GLOBAL_ULTIMATE_DUNS_NUMBER IN (SELECT U.GLOBAL_ULTIMATE_DUNS_NUMBER FROM U)
