WITH

MR AS (
    SELECT
        UPPER(CONCAT(E.OWNING_BRANCH_CODE,E.GCI_NUMBER)) AS "EVENT_KEY",
        MAX(E.INSERT_DTTM) AS "INSERT_DTTM"
    FROM
        SALES.COMPANY_EVENT E
    WHERE
        E.COMPANY_EVENT_TYPE_CODE = 'STRG_INITIATV_IDNTFR'
        -- AND UPPER(E.COMPANY_EVENT_DESCRIPTION) IN ('STARTUPS')
    GROUP BY
        UPPER(CONCAT(E.OWNING_BRANCH_CODE,E.GCI_NUMBER))
),

CON AS (
    SELECT
        CON.COMPANY_EVENT_ID AS "COMPANY_EVENT_ID",
        MAX(CON.INSERT_DTTM) AS "INSERT_DTTM"
    FROM
        SALES.INTERNAL_COMPANY_EVENT_CONTACTS_LINK CON
    GROUP BY
        CON.COMPANY_EVENT_ID
)

SELECT
    UPPER(CONCAT(
        EC.EMPLOYEE_ID,
        CASE
            WHEN C.CUSTOMER_ORGANIZATION_ID = 'UNGROUPED' THEN E.GCI_NUMBER
            ELSE C.CUSTOMER_ORGANIZATION_ID
        END
    )) AS "REPORT_KEY",
    E.OWNING_BRANCH_CODE AS "DISTRICT",
    CASE
        WHEN E.OWNING_BRANCH_CODE IN('NOG/NOX','CJS/ELP') THEN 'MEXICO/SOUTHERN BORDER'
        ELSE B.REGION_PL_NAME
    END AS "REGION",
    B.REGION_GEO_NAME1 AS "GEO",
    UPPER(C.MASTER_CLIENT_REPORTING) AS "ACCOUNT_NAME",
    CASE
        WHEN C.CUSTOMER_ORGANIZATION_ID = 'UNGROUPED' THEN E.GCI_NUMBER
        ELSE C.CUSTOMER_ORGANIZATION_ID
    END AS "ACCOUNT_ID",
    MIN(E.COMPANY_EVENT_DATE) AS "START_DATE",
    EC.EMPLOYEE_ID AS "EMPLOYEE_ID",
    CASE
        WHEN C.CUSTOMER_ORGANIZATION_ID = 'UNGROUPED' THEN 'GCI'
        ELSE 'ACCOUNT'
    END AS "ACCOUNT_TYPE",
    CASE
        WHEN E.CUSTOMER_ACCOUNT_MANAGEMENT_LEVEL_CODE IS NULL THEN 'SALES PIPELINE'
        ELSE E.CUSTOMER_ACCOUNT_MANAGEMENT_LEVEL_CODE
    END AS "ACC_MANAGEMENT",
    E.CUSTOMER_ACCOUNT_OWNER_EMPLOYEE_ID AS "OWNER",
    P.PARTICIPANT_NAME AS "OWNER_NAME",
    P.SALESPERSON_STATUS AS "SALESPERSON_STATUS",
    LISTAGG(DISTINCT T.TITLE_DESCRIPTION, ',') AS "OWNER_TITLE"
    ,E.GCI_NUMBER AS "GCI_NUMBER"
FROM
    SALES.COMPANY_EVENT E
INNER JOIN
    MR ON UPPER(CONCAT(E.OWNING_BRANCH_CODE,E.GCI_NUMBER)) = MR.EVENT_KEY AND E.INSERT_DTTM = MR.INSERT_DTTM
INNER JOIN
    SALES.INTERNAL_COMPANY_EVENT_CONTACTS_LINK EC ON E.COMPANY_EVENT_ID = EC.COMPANY_EVENT_ID
INNER JOIN
    CON ON EC.COMPANY_EVENT_ID = CON.COMPANY_EVENT_ID AND EC.INSERT_DTTM = CON.INSERT_DTTM
INNER JOIN
    DIMENSIONS.NEW_CLIENT_DIMENSION C ON E.GCI_NUMBER = C.GCI AND C.CLIENT_ACTIVE_YN = 'Y'
INNER JOIN
    DIMENSIONS.NEW_BRANCH_DIMENSION B ON (LEFT(E.OWNING_BRANCH_CODE,3) = B.BRANCH_CODE OR RIGHT(E.OWNING_BRANCH_CODE,3) = B.BRANCH_CODE) AND B.OPERATIONAL_BRANCH_INDICATOR = 'Y'
LEFT JOIN 
    DIMENSIONS.PARTICIPANT_DIMENSION P ON P.EMPLOYEE_ID = E.CUSTOMER_ACCOUNT_OWNER_EMPLOYEE_ID
LEFT JOIN
    DIMENSIONS.TITLE_DIMENSION T ON T.TITLE_KEY= P.PARTICIPANT_TITLE_KEY
WHERE
    E.ACCOUNT_ID = '${Account_Id}'
GROUP BY
    E.CUSTOMER_ACCOUNT_MANAGEMENT_LEVEL_CODE,
    E.CUSTOMER_ACCOUNT_OWNER_EMPLOYEE_ID,
    P.PARTICIPANT_NAME,
    P.SALESPERSON_STATUS,
    UPPER(CONCAT(EC.EMPLOYEE_ID,CASE WHEN C.CUSTOMER_ORGANIZATION_ID = 'UNGROUPED' THEN E.GCI_NUMBER ELSE C.CUSTOMER_ORGANIZATION_ID END)),
    E.OWNING_BRANCH_CODE,
    CASE WHEN E.OWNING_BRANCH_CODE IN('NOG/NOX','CJS/ELP') THEN 'MEXICO/SOUTHERN BORDER' ELSE B.REGION_PL_NAME END,
    B.REGION_GEO_NAME1,
    UPPER(C.MASTER_CLIENT_REPORTING),
    CASE WHEN C.CUSTOMER_ORGANIZATION_ID = 'UNGROUPED' THEN E.GCI_NUMBER ELSE C.CUSTOMER_ORGANIZATION_ID END,
    EC.EMPLOYEE_ID,
    CASE WHEN C.CUSTOMER_ORGANIZATION_ID = 'UNGROUPED' THEN 'GCI' ELSE 'ACCOUNT' END
    ,E.GCI_NUMBER