SELECT
    COUNT(DISTINCT N.GCI) AS "Total_GCI_Matches"
FROM
    DIMENSIONS.NEW_CLIENT_DIMENSION N
LEFT JOIN
    SALES.DUNS_MARKET_INSIGHT D ON N.DUNS_NUMBER = D.DUNS_NUMBER
LEFT JOIN
    SALES.MEETING M ON N.GCI = M.GCI_NUMBER AND M.STATUS_CODE = 'COMPLETED' AND DATE(M.MEETING_START_DATE_TIME) >= DATE(DAYS(CURRENT_DATE) - 365)
LEFT JOIN
    SALES.OPPORTUNITY O ON N.GCI = O.GCI_NUMBER AND M.OWNING_BRANCH_CODE = O.OWNING_BRANCH_CODE AND DATE(O.LAST_MODIFICATION_DATE_TIME) >= DATE(DAYS(CURRENT_DATE) - 365)
LEFT JOIN
    DIMENSIONS.NEW_BRANCH_DIMENSION B ON M.OWNING_BRANCH_CODE = B.BRANCH_CODE AND OPERATIONAL_BRANCH_INDICATOR = 'Y'
WHERE
    N.CLIENT_ACTIVE_YN = 'Y' AND (N.GCI LIKE 'G%' OR N.GCI LIKE '0%') AND (N.CUSTOMER_ORGANIZATION_ID = '${Account_Id}' OR N.MASTER_CLIENT_NUMBER = '${Account_Id}')
